name: Deploy UI5 App to GitHub Pages

on:
  push:
    branches:
      - main # ou 'master', dependendo do nome da sua branch principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build UI5 Project (Transpile TS to JS)
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta gerada pelo comando 'ui5 build'
          branch: gh-pages # Branch automática onde o site estático ficará